### ISSUE TITLE
Request to use as template for personal website

### ISSUE THREAD

**Issue by ashishnitinpatil** [xtonousou/xtonousou.github.io#7]
Hi,

Your website looks pretty cool and is responsive too. Since there was no mention of any license, I would like to know if I could use your website as a template for my own? I would attribute it by forking and having an HTML meta tag at least, unless you want something else. Kindly let me know.

Regards,
Ashish

**Comment by xtonousou** [comment]
I'm glad that you liked the website!

Yeah sure, fork it and use it as you want.

If you don't mind mention me as the author of the template, in anyway (meta tags, a small footer, or whatever is indexable), it's up to you 😊

**Comment by ashishnitinpatil** [comment]
Thank you so much! I'll link the site when I host it (with attribution) with your beautiful template :)

**Comment by ashishnitinpatil** [comment]
Thanks again! My site is up at https://ashishnitinpatil.github.io/ and I've kept a copyright icon attribution to you :)

**Comment by xtonousou** [comment]
Very nice! Thanks for the mention.
